W8D1/RedditClone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: redirect('/subs')
  
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  resources :subs, except: [:destroy]  
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end
  resources :comments, only: [:create]
end

W8D1/RedditClone/app/models/post.rb
class Post < ApplicationRecord
    validates :title, :author, presence: true    

    belongs_to :author,
        foreign_key: :author_id,
        class_name: :User

    # inverse_of is added here so when post is created, the association
    # is added to post_subs, even though post.id is nil
    has_many :post_subs, dependent: :destroy, inverse_of: :post

    has_many :subs,
        through: :post_subs,
        source: :sub

    has_many :comments,
        foreign_key: :post_id,
        class_name: :Comment
end

W8D1/RedditClone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :require_sign_in, except: [:index, :show]
    before_action :require_post_owner, only: [:edit, :update]

    def new
        @post = Post.new 
        render :new
    end

    def  create
        # set up the author id directly is not good, instead
        # put it in the whitelist params and used the current_user.post
        # @post = Post.new(post_params)   
        # @post.author_id = current_user.id  
        
        @post = current_user.posts.new(post_params)

        if @post.save
            redirect_to post_url(@post)
        else
            flash[:errors] = @post.errors.full_messages
            render :new
        end
    end

    def show
        @post = Post.find(params[:id])
        render :show
    end

    def edit
        @post = Post.find(params[:id])
        render :edit
    end

    def update
        @post = Post.find(params[:id])

        if @post.update(post_params)
            redirect_to post_url(@post)
        else
            flash[:erros] = @post.errors.full_messages
            render :edit 
        end 
    end

    private

    def post_params
        params.require(:post).permit(:title, :url, :content, :author_id, sub_ids: [])
    end

    def require_post_owner
        return if current_user.posts.find(params[:id])
        render json: 'Forbidden', status: :forbidden
    end
end

W8D1/RedditClone/app/helpers/posts_helper.rb
module PostsHelper
end

W8D1/RedditClone/app/views/posts/_form.html.erb
<% action_url = post.persisted? ? post_url(post) : posts_url %>
<% method_verb = post.persisted? ? "patch" : "post" %>
<% button_text = post.persisted? ? "Update Post" : "Create Post" %>

<form action="<%= action_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="<%= method_verb %>">

    <label>
        Title 
        <input type="text" name="post[title]" value="<%= post.title %>">
    </label> <br>
    <label>
        URL 
        <input type="text" name="post[url]" value="<%= post.url %>">
    </label> <br>
    <label>
        Content 
        <input type="text" name="post[content]" value="<%= post.content %>">
    </label> <br>

    <input type="hidden" name="post[sub_ids][]" value="" >
    <% Sub.all.each do |sub| %>
      <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>" 
        <%= post.sub_ids.include?(sub.id) ? "checked" : "" %> 
      >
      <%= sub.title  %>
      <br>
    <% end %>

    <input type="submit" value="<%= button_text %>">
</form>

W8D1/RedditClone/app/views/posts/edit.html.erb
<div class="border">
  <h1>Edit Post</h1>
  <%= render "form", post: @post %>
</div>

W8D1/RedditClone/app/views/posts/new.html.erb
<div class="border">
  <h1>New Post!</h1>
  <%= render "form", post: @post %>
</div>

W8D1/RedditClone/app/views/posts/show.html.erb
<div class="border">
    <h1><%= link_to @post.title, post_url(@post) %> by <%= @post.author.username %></h1>
    <div class="small-border">
        <p>Content:</p>
        <%= @post.content %>
    </div>

    <h3>Subs</h3>
    <ul>
        <% @post.subs.each do |sub| %>
          <li><%= link_to sub.title, sub_url(sub) %></li>
        <% end %>
    </ul>
    <h2>Comments</h2>
    <%= link_to "Comment on this post!", new_post_comment_url(@post) %>
    <ul>
        <li></li>
    </ul>
<div>