W8D1/RedditClone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: redirect('/subs')
  
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  resources :subs, except: [:destroy]  
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
  end
  resources :comments, only: [:create]
end

W8D1/RedditClone/app/models/sub.rb
class Sub < ApplicationRecord
    validates :title, :description, :moderator_id, presence: true

    belongs_to :moderator,
        foreign_key: :moderator_id,
        class_name: :User
    
    has_many :post_subs, dependent: :destroy

    has_many :posts,
        through: :post_subs,
        source: :post
    
end

W8D1/RedditClone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
    before_action :require_sign_in, except: [:index, :show]
    before_action :require_sub_owner, only: [:edit, :update]

    def new
        @sub = Sub.new
        render :new
    end

    def create
        @sub = Sub.new(sub_params)
        @sub.moderator_id = current_user.id

        if @sub.save 
            redirect_to sub_url(@sub)
        else
            flash[:errors] = @sub.errors.full_messages 
            render :new 
        end
    end

    def index
        @subs = Sub.all
        render :index
    end

    def show
        @sub = Sub.find(params[:id])
        render :show
    end

    def edit
        @sub = Sub.find(params[:id])
        render :edit
    end

    def update
        @sub = Sub.find(params[:id])

        if @sub.update(sub_params)
            redirect_to sub_url(@sub)
        else
            flash[:erros] = @sub.errors.full_messages
            render :edit 
        end
    end
    
    private

    def sub_params 
        params.require(:sub).permit(:title, :description)
    end

    def require_sub_owner
        return if current_user.subs.find(params[:id])
        render json: 'Forbidden', status: :forbidden
    end
end

W8D1/RedditClone/app/helpers/subs_helper.rb
module SubsHelper
end

W8D1/RedditClone/app/views/subs/_form.html.erb
<% action_url = sub.persisted? ? sub_url(sub) : subs_url %>
<% method_verb = sub.persisted? ? "patch" : "post" %>
<% button_text = sub.persisted? ? "Update Sub" : "Create Sub" %>

<form action="<%= action_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="<%= method_verb %>">

    <label>
        Title 
        <input type="text" name="sub[title]" value="<%= sub.title %>">
    </label> <br>
    <label>
        Description 
        <textarea name="sub[description]" id="" cols="30" rows="10">
            <%= sub.description %>
        </textarea>        
    </label> <br>
    <input type="submit" value="<%= button_text %>">
</form>

W8D1/RedditClone/app/views/subs/edit.html.erb
<div class="border">
  <h1>Create a new sub!</h1>
  <%= render "form", sub: @sub %>
</div>

W8D1/RedditClone/app/views/subs/index.html.erb
<h1>All the Subs!</h1>

<ul>
    <% @subs.each do |sub| %>
      <li>
        <a href="<%= sub_url(sub)%>"><%= sub.title %></a>        
      </li>
    <% end %>
</ul>

W8D1/RedditClone/app/views/subs/new.html.erb
<div class="border">
  <h1>Create a new sub!</h1>
  <%= render "form", sub: @sub %>
</div>

W8D1/RedditClone/app/views/subs/show.html.erb
<div class="border">
    <h1><%= @sub.title %></h1>
    <p><b>Description</b></p>
    <p><%= @sub.description %></p>
    <a href="<%= new_post_url %>">Make New Post!</a>
    <!-- <a href="<%= edit_sub_url(@sub) %>">Edit</a> -->

    <ul>
        <% @sub.posts.each do |post| %>
        <li><%= link_to post.title, post_url(post)  %></li>
        <% end %>
    </ul>
</div>